### ISSUE TITLE
Help with non-FBS binary files decoding

### ISSUE THREAD

**Issue by isHarryh** [MooncellWiki/OpenArknightsFBS#11]
得益于 OpenArknightsFBS 项目，已顺利完成对 FBS 格式的二进制数据文件的解析，在此表示感谢。

但是正如 README 所说，并不是所有的数据文件都使用了 FBS。例如 CN `gamedata/excel` 中的 `audio_data` `battle_equip_table` `display_meta_table` 不属于 FBS 格式。

特此询问 **解析非 FBS 数据文件的方法**。

**Comment by ashleney** [comment]
文件为 JSON 或 [BSON](https://www.mongodb.com/resources/languages/bson) 格式，使用 AES 加密

**Comment by isHarryh** [comment]
> 文件为 JSON 或 [BSON](https://www.mongodb.com/resources/languages/bson) 格式，使用 AES 加密

非常感谢您的指引！我已顺利完成非 FBS 数据文件的解析。
