### ISSUE TITLE
Feat: CN 2.0.01 适配

### ISSUE THREAD

**Issue by StarHeartHunt** [MooncellWiki/OpenArknightsFBS#5]
# List
- [x] activity_table
- [x] building_data
- [x] campaign_table
- [x] chapter_table
- [x] character_table
- [x] charword_table
- [x] enemy_database
- [x] handbook_info_table
- [x] medal_table
- [x] open_server_table
- [x] roguelike_topic_table
- [x] sandbox_table
- [x] shop_client_table
- [x] skill_table
- [x] stage_table

**Comment by yesod30** [comment]
I'm currenty working on mapping activity_table
